#git branch is mentioned
trigger:
- master

#Agent machine on which these jobs will run
pool:
  vmImage: 'ubuntu-latest'

# Pipelines > Stages > Jobs > Tasks (Steps)

jobs:
  - job: Job1
    steps: 
    - bash: echo Job1 - Hello, World, Changed!
      displayName: 'Run a one-line script'
      # | pipe symbol is used for running the multiple commands
    - script: |
        echo Will add tasks to build, test and deploy
        echo Hello Piyush
      displayName: 'Run the multi-line script'
  - job: Job2
    # dependsOn is break the parallel execution of Jobs. Now the Job2 will on run after Job1 is completed
    #dependsOn: Job1
    steps:
      - script: echo Job2!
        displayName: 'Run a one-line script'
  - job: Job3
    # dependsOn is break the parallel execution of Jobs. Now the Job3 will on run after Job1 is completed
    #dependsOn: Job1
    steps:
      - script: echo Job3!
        displayName: 'Run a one-line script'
  - job: Job4
    # dependsOn is break the parallel execution of Jobs. Now the Job4 will on run after Job2 and Job3 are completed
    #dependsOn: 
    #- Job2 
    #- Job3  
    steps:
      - script: echo Job4!
        displayName: 'Run a one-line script'
