#git branch is mentioned
trigger:
- master

#Agent machine on which these jobs will run
pool:
  vmImage: 'ubuntu-latest'

# Pipelines > Stages > Jobs > Tasks (Steps)

jobs:
  - job: Job1
    steps: 
    - script: echo Job1 - Hello, World, Changed!
      displayName: 'Run a one-line script'
    - script: |
        echo Will add tasks to build, test and deploy
        echo Hello Piyush
      displayName: 'Run the multi-line script'
  - job: Job2
    steps:
      - script: echo Job2!
        displayName: 'Run a one-line script'
  - job: Job3
    steps:
      - script: echo Job3!
        displayName: 'Run a one-line script'
  - job: Job4
    steps:
      - script: echo Job4!
        displayName: 'Run a one-line script'
